@startumlabstract class AbstractListabstract AbstractCollectioninterface Listinterface CollectionList <|-- AbstractListCollection <|-- AbstractCollectionCollection <|- ListAbstractCollection <|- AbstractListAbstractList <|-- ArrayListclass ArrayList {Object[] elementDatasize()}enum TimeUnit {DAYSHOURSMINUTES}TeacherFactory <|-- Teacherclass Teacher extends Person {	String number	String getNumber()    void setNumber(String number)	Teacher(String name, int age, String sex,String number)	Teacher()}class TeacherFactory {	Map<String,Teacher> pool	TeacherFactory()	Teacher getTeacher(String number)}@enduml